name: 'CDP Build Test Action'

description: 'builds and publishes docker image to ECR only'

inputs:
  version:
    description: 'overrides auto-versioning'
    required: false
    default: ''
  image-name:
    description: 'image of image to push (defaults to repo name)'
    required: false
    default: ${{ github.event.repository.name }}
  push:
    description: 'push docker image after building'
    required: false
    default: true
  github-token:
    description: Github Token, required for autoversioning
    required: false
  secret-manager-docker-credentials:
    description: Secret for Github Actions to run Terraform
    default: cdp/platform/gh_actions

runs:
  using: "composite"
  steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-${{ inputs.image-name }}-build-role

    - run: aws sts get-caller-identity
      shell: bash

    # Get Docker secrets from Secrets Manager
    - name: Get Github Actions secrets from Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ,${{ inputs.secret-manager-docker-credentials }}
        parse-json-secrets: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME}}
        password: ${{ env.DOCKER_TOKEN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: auto-version
      id: version
      if: inputs.version == ''
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WITH_V: false
        DRY_RUN: true

    - name: Docker Build
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        no-cache: true
        file: ./Dockerfile
        push: ${{ inputs.push }}
        tags: |
          ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:${{ steps.version.outputs.new_tag || inputs.version }}
          ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:latest
        labels: |
          defra.cdp.git.repo.url=${{ github.server_url }}/${{ github.repository }}
          defra.cdp.git.repo.name=${{ github.repository }}
          defra.cdp.testsuite.name=${{ inputs.image-name }}
          defra.cdp.build.run_id=${{ github.run_id }}
          defra.cdp.run_mode=job
          git.hash=${{ github.sha }}

    - name: commit-version
      if: inputs.version == '' && inputs.push
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WITH_V: false
