name: "CDP Secrets Manager Placeholder Creation"
description: "Triggers updates to create Secrets Manager placeholders for services"

inputs:
  topicArn:
    description: Which sns topic to send the message to
    required: true
  targetEnv:
    description: The target environment for the tenant_services.json
    required: true

runs:
  using: "composite"
  steps:
    - name: Construct filtered_secrets_payload.json from multiple files
      shell: bash
      run: |
        echo "Filtering Secrets Manager services for environment: ${{ inputs.targetEnv }}"
        python ${{ github.action_path }}/filter_secrets_payload.py ${{ inputs.targetEnv }}

    - name: Manage Secrets Manager Secrets
      shell: bash
      run: |
        message_id=$(uuidgen)
        json_file="environments/${{ inputs.targetEnv }}/filtered_secrets_payload.json"
        echo "Publishing filtered Secrets Manager payload to SNS"
        aws sns publish --topic-arn ${{ inputs.topicArn }}  --message-attributes \
        '{"environment" : { "DataType":"String", "StringValue":"${{ inputs.targetEnv }}"}}' \
        --message file://$json_file \
        --message-group-id "${{ inputs.targetEnv }}" --message-deduplication-id ${message_id}
