name: "CDP Secrets Manager Placeholder Creation"
description: "Triggers updates to create Secrets Manager placeholders for services"

inputs:
  topicArn:
    description: Which sns topic to send the message to
    required: true
  targetEnv:
    description: The target environment for the tenant_services.json
    required: true

runs:
  using: "composite"
  steps:
    - name: Construct merged_tenant_services.json from multiple files
      shell: bash
      run: |
        merged_file=environments/${{ inputs.targetEnv }}/merged_tenant_services.json
        echo "[" > $merged_file

        first=true
        for file in environments/${{ inputs.targetEnv }}/tenants/*.json; do
          if [ "$first" = true ]; then
            first=false
          else
            echo "," >> $merged_file
          fi
          service_name=$(basename "$file" .json)
          echo "{\"$service_name\": $(cat $file)}" >> $merged_file
        done

        echo "]" >> $merged_file

    - name: Manage Secrets Manager Secrets
      shell: bash
      run: |
        message_id=$(uuidgen)
        json_file="environments/${{ inputs.targetEnv }}/merged_tenant_services.json"
        aws sns publish --topic-arn ${{ inputs.topicArn }}  --message-attributes \
        '{"environment" : { "DataType":"String", "StringValue":"${{ inputs.targetEnv }}"}}' \
        --message file://$json_file \
        --message-group-id "${{ inputs.targetEnv }}" --message-deduplication-id ${message_id}
