# This multiple situation is being worked on as of April 2024 - https://github.com/dependabot/dependabot-core/issues/2178
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/build"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/build-private"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/build-test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/check-pr"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/apply"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/elasticache-redis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/format"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/init"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/mongo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/plan"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/plan-no-lock"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/secrets"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/secrets-manager"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/tf-build/validate"
    schedule:
      interval: "weekly"
