name: 'Raise Pull Request'
description: 'Creates a pull request for the specified branch if one does not already exist.'
inputs:
  branch_name:
    description: 'The name of the branch to create the PR for.'
    required: true
  pr_title:
    description: 'The title of the pull request.'
    required: true
  pr_body:
    description: 'The body/description of the pull request.'
    required: true
    default: "Automated Pull Request from Composite Action"
  base_branch:
    description: 'The base branch to merge into (default: main).'
    required: false
    default: 'main'
outputs:
  pr_url:
    description: 'The URL of the created or existing pull request.'
    value: ${{ steps.raise-pr.outputs.pr_url }}
  pr_number:
    description: 'The number of the created or existing pull request.'
    value: ${{ steps.raise-pr.outputs.pr_number }}
runs:
  using: 'composite'
  steps:
    - name: Check for existing PR
      id: check-pr
      shell: bash
      run: |
        # Remove leading and trailing spaces
        branch_name=$(echo "${{ inputs.branch_name }}" | xargs)

        # Check if a PR already exists for the branch
        EXISTING_PR=$(gh pr list --head "${branch_name}" --json number,url --jq '.[0]')
        if [[ -n "$EXISTING_PR" ]]; then
          echo "PR already exists for branch ${branch_name}."
          PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.number')
          PR_URL=$(echo "$EXISTING_PR" | jq -r '.url')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "No existing PR found. Will create one."
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create PR if none exists
      id: raise-pr
      shell: bash
      if: steps.check-pr.outputs.exists == 'false'
      run: |
        # Create the pull request
        # Remove leading and trailing spaces
        branch_name=$(echo "${{ inputs.branch_name }}" | xargs)
        PR_OUTPUT=$(gh pr create \
          --title "${{ inputs.pr_title }}" \
          --body "${{ inputs.pr_body }}" \
          --base "${{ inputs.base_branch }}" \
          --head "${branch_name}")
