name: 'Commit and Push Changes'
description: 'Commits and pushes changes with retry logic, optionally to a specified branch (creating it if it does not exist).'
inputs:
  commit_message:
    description: 'The commit message to use.'
    required: true
  branch_name:
    description: 'Name of the branch to commit to. If not provided, uses the current branch. Creates the branch if it does not exist.'
    required: false
outputs:
  branch_name:
    description: 'The name of the branch that was committed to.'
    value: ${{ steps.commit.outputs.branch_name }}
runs:
  using: 'composite'
  steps:
    - name: Commit and push changes
      id: commit
      shell: bash
      run: |
        # Determine the target branch
        if [[ -n "${{ inputs.branch_name }}" ]]; then
          TARGET_BRANCH="${{ inputs.branch_name }}"
          COMMIT_MESSAGE="${{ inputs.commit_message }}"
        else
          TARGET_BRANCH="$GITHUB_REF"
          COMMIT_MESSAGE="${{ inputs.commit_message }} [skip ci]"
        fi
        
        attempts=0
        while (( attempts++ <= 3 )); do
          # Add, commit, and push changes
          git add -A && \
          git commit -m "$COMMIT_MESSAGE" && \
          
          # Push to the target branch
          if git push origin "$TARGET_BRANCH"; then
            echo "branch_name=$TARGET_BRANCH" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Failed to push changes, retrying..."
            sleep 1
            git reset --hard HEAD^
            git pull origin "$TARGET_BRANCH"
          fi
        done
        echo "Failed to commit and push after 3 attempts."
        exit 1