name: "CDP Terraform Init"
description: "Prepare Environment for Terraform Run"

inputs:
  tf_path:
    description: 'A root directory with Terraform files'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: |
        cd ${{ inputs.tf_path }}
        terraform init -backend-config environments/${{ env.ENVIRONMENT }}/backend.conf -reconfigure --upgrade
      shell: bash

    - name: Post init
      if: always() && github.ref != 'refs/heads/main' && steps.init.outcome == 'success' || steps.init.outcome == 'failure'
      uses: Jimdo/terraform-pr-commenter@v1.6.0
      with:
        commenter_type: init
        commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
        commenter_exitcode: ${{ steps.init.outputs.exitcode }}
        commenter_comment: "Environment: ${{ env.ENVIRONMENT }}"
