name: 'Upload Plan Artifact'
description: 'Uploads a Terraform plan artifact from a PR workflow'

inputs:
  environment:
    description: 'The environment name (e.g., dev, prod)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload Plan Artifact
      id: upload
      uses: actions/upload-artifact@v7.0.1 # Upgrade version here to update all pipelines using this action
      with:
        name: ${{ inputs.environment }}.plan.file
        path: ${{ inputs.environment }}.plan.file
        retention-days: 1