name: "CDP Terraform Plan"
description: "Runs a Terraform Plan"

inputs:
  tf_path:
    description: 'A root directory with Terraform files'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      shell: bash
      run: |
        ${{ github.action_path }}/plan.sh "${{ inputs.tf_path }}"

    - name: Post Comment if Plan is Large
      if: steps.plan.outputs.plan_is_large == 'true'
      shell: bash
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ${{ env.ENVIRONMENT }}.tf_plan.txt)"

    - name: Post Comment if Plan is Normal
      if: steps.plan.outputs.plan_is_large == 'false'
      uses: DEFRA/cdp-terraform-pr-commenter@master
      env:
        TF_WORKSPACE: ${{ env.ENVIRONMENT }}
      with:
        commenter_type: plan
        commenter_input: ${{ steps.plan.outputs.plan_text }}
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
