name: 'CDP Build Hot Fix Action'

description: 'Builds and publishes docker image to ECR and DockerHub from a branch as a patch release'

inputs:
  image-name:
    description: 'image of image to push (defaults to repo name)'
    required: false
    default: ${{ github.event.repository.name }}
  push:
    description: 'push docker image after building'
    required: false
    default: true
  github-token:
    description: Github Token, required for autoversioning
    required: false
    default: ${{ github.token }}
  secret-manager-docker-credentials:
    description: Secret for Github Actions to run Terraform
    default: cdp/platform/gh_actions
  sbom-bucket:
    description: 'Name of the SBOM bucket'
    required: true
    default: cdp-management-sbom
  dev-stage:
    description: 'Name of the development/build stage in dockerfile to extract the SBOM from'
    required: false
    default: development
  publish-sbom:
    description: 'Enables SBOM publishing'
    required: false
    default: false
  publish-dev-sbom:
    description: 'Enabled or disables publishing the dev stage of the SBOM'
    required: false
    default: false


runs:
  using: "composite"
  steps:
    - name: Cannot run on main
      if: ${{ github.ref == 'refs/heads/main' }}
      shell: bash
      run: |
        echo "You cannot do hotfixes from the main branch!"
        exit 1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-${{ inputs.image-name }}-build-role

    - run: aws sts get-caller-identity
      shell: bash

    # Get Docker secrets from Secrets Manager
    # NOTE: the `,` in the secret-id param is intentional and not a typo
    - name: Get Github Actions secrets from Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ,${{ inputs.secret-manager-docker-credentials }}
        parse-json-secrets: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME}}
        password: ${{ env.DOCKER_TOKEN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: List tags
      shell: bash
      run: git tag --list --merged HEAD --sort=-committerdate --format='%(refname:strip=2) - %(objectname) - %(committerdate)'

    - name: auto-version
      id: version
      uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WITH_V: false
        DRY_RUN: true
        DEFAULT_BUMP: patch
        TAG_CONTEXT: branch

    - name: Docker Build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      with:
        context: .
        no-cache: true
        file: ./Dockerfile
        push: ${{ inputs.push }}
        load: true
        sbom: true
        tags: |
          ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ inputs.image-name }}:${{ steps.version.outputs.new_tag }}
          defradigital/${{ inputs.image-name }}:${{ steps.version.outputs.new_tag }}
        labels: |
          defra.cdp.git.repo.url=${{ github.server_url }}/${{ github.repository }}
          defra.cdp.git.repo.name=${{ github.repository }}
          defra.cdp.service.name=${{ inputs.image-name }}
          defra.cdp.build.run_id=${{ github.run_id }}
          defra.cdp.run_mode=service
          defra.cdp.hotfix=${{ steps.version.outputs.new_tag }}
          git.hash=${{ github.sha }}

    - name: Build SBOMs
      if: ${{ inputs.publish-sbom == 'true' }}
      uses: anchore/sbom-action@v0
      with:
        image: defradigital/${{ inputs.image-name }}:${{ steps.version.outputs.new_tag || inputs.version }}
        format: cyclonedx-json
        upload-artifact: true
        output-file: ./sbom.json

    - name: Publish SBOMs
      if: ${{ inputs.publish-sbom == 'true' }}
      shell: bash
      run:
         aws s3 cp ./sbom.json "s3://${{ inputs.sbom-bucket }}/${{ inputs.image-name }}/${{ steps.version.outputs.new_tag || inputs.version }}/sbom.json"

    - name: Build Dev Layer
      if: ${{ inputs.publish-dev-sbom == 'true' }}
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        target: ${{ inputs.dev-stage  }}
        tags: |
          devstage:latest

    - name: Build Dev SBOMs
      if: ${{ inputs.publish-dev-sbom == 'true' }}
      uses: anchore/sbom-action@v0
      with:
        image: devstage:latest
        format: cyclonedx-json
        upload-artifact: true
        output-file: ./sbom.dev.json

    - name: Publish Dev SBOMs
      if: ${{ inputs.publish-dev-sbom == 'true' }}
      shell: bash
      run:
         aws s3 cp ./sbom.dev.json "s3://${{ inputs.sbom-bucket }}/${{ inputs.image-name }}/${{ steps.version.outputs.new_tag || inputs.version }}/sbom.dev.json"

    - name: commit-version
      if: ${{ inputs.push == 'true' }}
      uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WITH_V: false
        DEFAULT_BUMP: patch
        TAG_CONTEXT: branch

