name: "CDP Elasticache Redis User Creation"
description: "Triggers updates to the Elasticache Redis Users"

inputs:
  topicArn:
    description: Which sns topic to send the message to
    required: true
  targetEnv:
    description: The target environment for the tenant_services.json
    required: true
runs:
  using: "composite"
  steps:
    - name: Construct filtered_redis_payload.json from multiple files
      shell: bash
      run: |
        echo "Filtering Redis services for environment: ${{ inputs.targetEnv }}"
        python ${{ github.action_path }}/filter_redis_payload.py ${{ inputs.targetEnv }}

    - name: Manage Redis Users
      shell: bash
      run: |
        message_id=$(uuidgen)
        json_file="environments/${{ inputs.targetEnv }}/filtered_redis_payload.json"
        echo "Publishing filtered Redis payload to SNS"
        aws sns publish --topic-arn ${{ inputs.topicArn }}  --message-attributes \
        '{"environment" : { "DataType":"String", "StringValue":"${{ inputs.targetEnv }}"}}' \
        --message file://$json_file \
        --message-group-id "${{ inputs.targetEnv }}" --message-deduplication-id ${message_id}
