name: "CDP Elasticache Redis User Creation"
description: "Triggers updates to the Elasticache Redis Users"

inputs:
  topicArn:
    description: Which sns topic to send the message to
    required: true
  targetEnv:
    description: The target environment for the tenant_services.json
    required: true
  mergeJsonFiles:
    description: "Merge JSON files to create tenant_services.json"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Check if JSON merge needed
      id: check_merge
      shell: bash
      run: echo "merge=${{ inputs.mergeJsonFiles }}" >> $GITHUB_ENV

    - name: Construct merged_tenant_services.json from multiple files
      if: ${{ env.merge == 'true' }}
      shell: bash
      run: |
        merged_file=environments/${{ inputs.targetEnv }}/resources/merged_tenant_services.json
        echo "[" > $merged_file

        first=true
        for file in environments/${{ inputs.targetEnv }}/tenants/*.json; do
          if [ "$first" = true ]; then
            first=false
          else
            echo "," >> $merged_file
          fi
          service_name=$(basename "$file" .json)
          echo "{\"$service_name\": $(cat $file)}" >> $merged_file
        done

        echo "]" >> $merged_file

    - name: Manage Redis Users
      shell: bash
      run: |
        message_id=$(uuidgen)
        json_file="environments/${{ inputs.targetEnv }}/resources/tenant_services.json"
        if [[ ${{ env.merge }} == 'true' ]]; then
          json_file="environments/${{ inputs.targetEnv }}/resources/merged_tenant_services.json"
        fi
        aws sns publish --topic-arn ${{ inputs.topicArn }}  --message-attributes \
        '{"environment" : { "DataType":"String", "StringValue":"${{ inputs.targetEnv }}"}}' \
        --message file://$json_file \
        --message-group-id "${{ inputs.targetEnv }}" --message-deduplication-id ${message_id}
