name: "CDP Terraform Plan - no lock"
description: "Runs a Terraform Plan without a lock"

runs:
  using: "composite"
  steps:
    # Generates an execution plan for Terraform
    - name: Terraform Plan - no lock
      id: plan
      run: terraform plan -input=false -var-file environments/${{ env.ENVIRONMENT }}/terraform.tfvars -compact-warnings -lock=false
      shell: bash

    #- name: Post Plan
    #  if: always() && github.ref != 'refs/heads/main' && steps.plan.outcome == 'success' || steps.plan.outcome == 'failure'
    #  uses: Jimdo/terraform-pr-commenter@v1.6.0
    #  with:
    #    commenter_type: plan
    #    commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
    #    commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
    #    commenter_comment: "Environment: ${{ env.ENVIRONMENT }}"
