name: "CDP Terraform Apply"
description: "Runs a Terraform Apply"

inputs:
  tf_path:
    description: 'A root directory with Terraform files'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Terraform Apply
      id: apply
      run: |
        cd ${{ inputs.tf_path }}
        terraform apply -input=false -compact-warnings ${{ env.ENVIRONMENT }}.plan.file
      shell: bash
