name: Push Docker Image to ECR
description: 'Push the Docker Image to ECR'
inputs:
  aws_account_id:
    description: AWS Account ID for the ECR repository
    required: true
  aws_region:
    description: AWS Region for the ECR repository, e.g. eu-west-2
    default: eu-west-2
    required: false
  image_name:
    description: Name of the image to push
    required: true
  tag:
    description: The tag being pushed
    required: true

runs:
  using: "composite"
  steps:
    - name: Push Container
      run: |
        docker push ${{inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.image_name }}:${{ inputs.tag }}
      shell: bash
