name: 'Centralized Checkout'
description: 'Wraps actions/checkout to manage versions and defaults in one place'

inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history.'
    required: false
    default: '1'
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
    default: ''
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
    default: 'main' # Defaulting to main as requested

runs:
  using: "composite"
  steps:
    - name: Execute Checkout
      uses: actions/checkout@v5 # Bump version here to update all pipelines using this action
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}