name: "CDP Terraform Validate"
description: "Run Terraform validate"

inputs:
  tf_path:
    description: 'A root directory with Terraform files'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    # Validates the configuration files in a directory
    - name: Terraform validate
      id: validate
      run: |
        cd ${{ inputs.tf_path }}
        terraform validate
      shell: bash

    - name: Post Validate
      if: always() && github.ref != 'refs/heads/main' && steps.validate.outcome == 'success' || steps.validate.outcome == 'failure'
      continue-on-error: true
      uses: DEFRA/cdp-terraform-pr-commenter@master
      with:
        commenter_type: validate
        commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
        commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
