name: "CDP Terraform Validate"
description: "Run Terraform validate"

runs:
  using: "composite"
  steps:
    # Validates the configuration files in a directory
    - name: Terraform validate
      id: validate
      run: terraform validate
      shell: bash

    - name: Post Validate
      if: always() && github.ref != 'refs/heads/main' && steps.validate.outcome == 'success' || steps.validate.outcome == 'failure'
      uses: Jimdo/terraform-pr-commenter@v1.6.0
      with:
        commenter_type: validate
        commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
        commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
        commenter_comment: "Environment: ${{ env.ENVIRONMENT }}"
