name: "CDP Terraform Format"
description: "Run Terraform format"

inputs:
  tf_path:
    description: 'A root directory with Terraform files'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: format
      run: |
        cd ${{ inputs.tf_path }}
        terraform fmt -check
      shell: bash

    - name: Post Format
      if: always() && github.ref != 'refs/heads/main' && steps.format.outcome == 'success' || steps.format.outcome == 'failure'
      uses: DEFRA/cdp-terraform-pr-commenter@master
      with:
        commenter_type: fmt
        commenter_input: ${{ format('{0}{1}', steps.format.outputs.stdout, steps.format.outputs.stderr) }}
        commenter_exitcode: ${{ steps.format.outputs.exitcode }}
