name: "CDP Terraform Format"
description: "Run Terraform format"

runs:
  using: "composite"
  steps:
    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: format
      run: terraform fmt -check
      shell: bash

    - name: Post Format
      if: always() && github.ref != 'refs/heads/main' && steps.format.outcome == 'success' || steps.format.outcome == 'failure'
      uses: Jimdo/terraform-pr-commenter@v1.6.0
      with:
        commenter_type: fmt
        commenter_input: ${{ format('{0}{1}', steps.format.outputs.stdout, steps.format.outputs.stderr) }}
        commenter_exitcode: ${{ steps.format.outputs.exitcode }}
        commenter_comment: "Environment: ${{ env.ENVIRONMENT }}"
