name: 'CDP Publish Database Migrations'

description: 'Publishes and versions liquibase migration files to to S3.'

inputs:
  path:
    description: 'path to the migration script folder'
    required: true
  version:
    description: 'overrides auto-versioning'
    required: false
    default: ''
  service-name:
    description: 'name of service to publish db  to push (defaults to repo name)'
    required: false
    default: ${{ github.event.repository.name }}
  bucket:
    description: S3 bucket to upload to
    required: true
    default: "cdp-infra-dev-database-migrations"
  github-token:
    description: Github Token, required for autoversioning
    required: false

runs:
  using: "composite"
  steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-${{ inputs.service-name }}-build-role

    - run: aws sts get-caller-identity
      shell: bash

    - name: Get current version
      id: version
      if: inputs.version == ''
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WITH_V: false
        DRY_RUN: true

    - name: Check if migrations folder exists and contains files
      shell: bash
      run: |
        if [ ! -d "${{ inputs.path }}" ]; then
        echo "❌ The path '${{ inputs.folder-path }}' does not exist or is not a directory."
        exit 1
        fi

        if [ -z "$(find "${{ inputs.path }}" -type f -print -quit)" ]; then
        echo "❌ The directory '${{ inputs.path }}' does not contain any files."
        exit 1
        fi

        echo "✅ Directory '${{ inputs.path }}' exists and contains at least one file."

    - name: Create tar.gz archive with preserved folder structure
      shell: bash
      run: |
        mkdir -p output
        tar -czf output/migrations.tgz -C "${{ inputs.path }}" .

    - name: Copy migrations tgz to S3
      shell: bash
      env:
        VERSION_TAG: ${{ steps.version.outputs.tag }}
      run: |
        echo "Publishing schema version ${VERSION_TAG}"
        aws s3 cp output/migrations.tgz "s3://${{ inputs.bucket }}/${{ inputs.service-name }}/${VERSION_TAG}/migrations.tgz"

