name: "CDP Mongo User Creation"
description: "Triggers update of mongo user roles"

inputs:
  topicArn:
    description: Which sns topic to send the message to

runs:
  using: "composite"
  steps:
    - name: Construct filtered_mongo_payload.json from multiple files
      shell: bash
      run: |
        echo "Filtering MongoDB services for environment: ${{ env.ENVIRONMENT }}"
        python ${{ github.action_path }}/filter_mongo_payload.py ${{ env.ENVIRONMENT }}

    - name: Update MongoDB Users
      shell: bash
      run: |
        json_file="environments/${{ env.ENVIRONMENT }}/filtered_mongo_payload.json"
        echo "Publishing filtered MongoDB payload to SNS"
        aws sns publish --topic-arn ${{ inputs.topicArn }} --message file://${json_file}
