name: "CDP Mongo User Creation"
description: "Triggers update of mongo user roles"

inputs:
  topicArn:
    description: Which sns topic to send the message to

runs:
  using: "composite"
  steps:
    - name: Construct merged_tenant_services.json from multiple files
      shell: bash
      run: |
        echo "Construct merged_tenant_services.json from multiple files"
        merged_file=environments/${{ env.ENVIRONMENT }}/merged_tenant_services.json
        echo "[{" > $merged_file

        first=true
        for file in environments/${{ env.ENVIRONMENT }}/tenants/*.json; do
          if [ "$first" = true ]; then
            first=false
          else
            echo "," >> $merged_file
          fi
          service_name=$(basename "$file" .json)
          echo "\"$service_name\": $(cat $file)" >> $merged_file
        done

        echo "}]" >> $merged_file

    - name: Update Mongodb Users
      shell: bash
      run: |
        json_file="environments/${{ env.ENVIRONMENT }}/merged_tenant_services.json"
        echo "Updating users with ${json_file}"
        aws sns publish --topic-arn ${{ inputs.topicArn }} --message file://${json_file}
