name: "CDP Mongo User Operations"
description: "Triggers MongoDB user operations (create/delete/refresh)"

inputs:
  topicArn:
    description: Which sns topic to send the message to
    required: true
  operation:
    description: 'Operation mode: create, delete, or refresh'
    required: true

runs:
  using: "composite"
  steps:
    - name: Construct filtered_mongo_payload.json from multiple files
      shell: bash
      run: |
        echo "Filtering MongoDB services for environment: ${{ env.ENVIRONMENT }}"
        python ${{ github.action_path }}/filter_mongo_payload.py ${{ env.ENVIRONMENT }}

    - name: Update MongoDB Users
      shell: bash
      run: |
        json_file="environments/${{ env.ENVIRONMENT }}/filtered_mongo_payload.json"
        echo "Publishing filtered MongoDB payload to SNS with operation: ${{ inputs.operation }}"
        aws sns publish \
          --topic-arn ${{ inputs.topicArn }} \
          --message file://${json_file} \
          --message-attributes '{"operation":{"DataType":"String","StringValue":"${{ inputs.operation }}"}}'
