name: 'Get GitHub Token'

description: 'Gets a github cert from AWS Secret Manager and extracts a PAT token and sets GH_ACTION'

inputs:
  role_to_assume:
    description: The IAM role to assume for fetching Secrets
    required: true
  app_id:
    description: GitHub app ID
    required: true
  private_key_id:
    description: Secret for GitHub App
    required: true
  aws_region:
    description: AWS Region
    default: eu-west-2

runs:
  using: "composite"
  steps:
    # Setup exectuion for AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.role_to_assume }}
    - run: aws sts get-caller-identity
      shell: bash

    # Get the private git
    - name: Get Github app private key from ASM
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          PRIVATE_KEY, ${{ inputs.private_key_id }}

    # Github auth using Github App - environment variables are set by previous step action
    - name: Get token
      id: get-token
      uses: getsentry/action-github-app-token@v3
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ env.PRIVATE_KEY }}

    # Set the GH_TOKEN environment variable, replacing the default token
    - name: export
      shell: bash
      env:
        TOKEN: ${{ steps.get-token.outputs.token }}
      run: |
        echo "GH_TOKEN=$TOKEN" >> $GITHUB_ENV
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/user/public_emails
