name: Tag a Docker Image
description: 'Tag the Docker Image'
inputs:
  aws_account_id:
    description: AWS Account ID for the ECR repository
    required: true
  aws_region:
    description: AWS Region for the ECR repository, e.g. eu-west-2
    default: eu-west-2
    required: true
  ecr_repo:
    description: ECR repository name
    required: true
  image_name:
    description: Name of the image to tag
    required: true
  local_tag:
    description: Local tag for the container image
    default: build
    required: false
  desired_tag:
    description: The tag to apply to the container image
    required: true

runs:
  using: "composite"
  steps:
    - name: Tag Container
      run: |
        echo "Tagging ${{ inputs.image_name }}:${{ inputs.local_tag }} with tag: ${{ inputs.desired_tag }}"
        docker tag ${{ inputs.image_name }}:${{ inputs.local_tag }} ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repo }}:${{ inputs.desired_tag }}
      shell: bash
