name: "CDP Terraform Secrets"
description: "Get secrets for Terraform"

inputs:
  gh_actions_secrets:
    description: Secret for Github Actions to run Terraform
    default: cdp/platform/gh_actions
  gh_app_private_key:
    description: Secret for Github App
    default: CDP_GH_APP_PRIV_KEY,cdp/platform/gh_apps/cdp-gh-action/private-key

runs:
  using: "composite"
  steps:
    # Setup exectuion for AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-role
    - run: aws sts get-caller-identity
      shell: bash

    # Get Github actions secrets from ASM
    - name: Get Github actions secrets from ASM
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          ${{ inputs.gh_actions_secrets }}
        parse-json-secrets: true

      # Get Github app private key from ASM
    - name: Get Github app private key from ASM
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          ${{ inputs.gh_app_private_key }}

    # Github auth using Github App - environment variables are set by previosu step action
    - name: get gh token from cdp-gh-action
      id: cdp-gh-action
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ env.CDP_PLATFORM_GH_ACTIONS_CDP_GH_APP_ID }}
        private_key: ${{ env.CDP_GH_APP_PRIV_KEY }}

    # Set Git Config using step output
    - name: git config url rewrite for internal repo access
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://x-access-token:${{ steps.cdp-gh-action.outputs.token }}@github.com".insteadOf "https://github.com"
        git config --list
      shell: bash
