name: 'CDP PR Validator Action'
description: 'checks docker image will build'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: ./docker-login/action.yml

    - name: Check Dockerfile Builds
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: false
