name: 'CDP Docker Login'
description: 'Logs into Docker Hub'

inputs:
  secret-manager-docker-credentials:
    description: Secret containing json with Docker credentials. Must contain docker_token and docker_username.
    default: cdp/platform/gh_actions

runs:
  using: "composite"
  steps:

    # Get Docker secrets from Secrets Manager
    - name: Get Github Actions secrets from Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          ,${{ inputs.secret-manager-docker-credentials }}
        parse-json-secrets: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME}}
        password: ${{ env.DOCKER_TOKEN }}
