name: 'CDP Docker Login'
description: 'Logs into Docker Hub'

inputs:
  iam-role-name:
    description: Role to assume to retrieve docker credentials from Secrets Manager
    default: github-${{ github.event.repository.name }}-build-role
  aws-region:
    description: AWS region
    default: eu-west-2
  aws-account-id:
    description: AWS account id
    default: "094954420758"
  secret-manager-docker-credentials:
    description: Secret containing json with Docker credentials. Must contain docker_token and docker_username.
    default: cdp/platform/gh_actions

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.iam-role-name }}

    - run: aws sts get-caller-identity
      shell: bash

    # Get Docker secrets from Secrets Manager
    - name: Get Github Actions secrets from Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ,${{ inputs.secret-manager-docker-credentials }}
        parse-json-secrets: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME}}
        password: ${{ env.DOCKER_TOKEN }}
